export const itemData = [
  {
    id: '01',
    title: 'D-Brand',
    subTitle: 'Slim-fit Solid Casual Shirt',
    color: 'blue',
    wishListed: false,
    sizes: ['XS','S','M','L','XL','XL'],
    sizesAvailable:['S','M','L','XL','XL'],
    pattern:'solid',
    sleeves: 'full',
    texture:'cotton',
    category:'Shirts',
    type:'casual',
    price: '1499',
    imageURL:
      'https://i.ibb.co/0rX0YmM/creating-a-brand-xc-QWU0-Eff-U-unsplash.jpg',
  },
  {
    id: '01',
    title: 'D-Brand',
    subTitle: 'Slim-fit Solid Casual Shirt',
    color: 'blue',
    wishListed: false,
    sizes: ['XS','S','M','L','XL','XL'],
    sizesAvailable:['S','M','L','XL','XL'],
    pattern:'solid',
    sleeves: 'full',
    texture:'cotton',
    category:'Shirts',
    type:'casual',
    price: '1499',
    imageURL:
      'https://i.ibb.co/0rX0YmM/creating-a-brand-xc-QWU0-Eff-U-unsplash.jpg',
  },
  {
    id: '01',
    title: 'D-Brand',
    subTitle: 'Slim-fit Solid Casual Shirt',
    color: 'blue',
    wishListed: false,
    sizes: ['XS','S','M','L','XL','XL'],
    sizesAvailable:['S','M','L','XL','XL'],
    pattern:'solid',
    sleeves: 'full',
    texture:'cotton',
    category:'Shirts',
    type:'casual',
    price: '1499',
    imageURL:
      'https://i.ibb.co/0rX0YmM/creating-a-brand-xc-QWU0-Eff-U-unsplash.jpg',
  },
];
